stages:
  - lint
  - test
  - build

lint_terraform:
  stage: lint
  image: docker
  script:
    - wget -P /tmp https://github.com/wata727/tflint/releases/download/v0.7.5/tflint_linux_amd64.zip
    - unzip -o -d /usr/local/bin/ /tmp/tflint_linux_amd64.zip
    - wget -P /tmp https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    - unzip -o -d /usr/local/bin/ /tmp/terraform_0.11.11_linux_amd64.zip
    - cd terraform
    - cp terraform.tfvars.example terraform.tfvars
    - terraform get
    - terraform init
    - terraform validate
    - tflint
  only:
    - triggers
    - branches

lint_dockerfile:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - find . -name "Dockerfile*" | xargs hadolint
  only:
    - triggers
    - branches

test_ui:
  stage: test
  image: python:3.6.8-alpine3.8
  script:
    - cd src/search_engine_ui
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py
  only:
    - triggers
    - branches

test_crawler:
  stage: test
  image: python:3.6.8-alpine3.8
  script:
    - cd src/search_engine_crawler
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include crawler/crawler.py
  only:
    - triggers
    - branches
