---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "crawler.fullname" . }}
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "crawler.fullname" . }}
        ports:
        - name: crawler
          containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: crawler
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: crawler
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: RMQ_HOST
          value: {{ .Values.messageBrokerHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_USERNAME
          value: {{ .Values.rabbitmq.username }}
        - name: RMQ_PASSWORD
          value: {{ .Values.rabbitmq.password }}
        - name: EXCLUDE_URLS
          value: {{ .Values.excludeURLs }}
        - name: URL
          value: {{ .Values.url }}

